version: '2.1'
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    docker:
      - image: circleci/node
      - image: circleci/mongo:4.1.9
    steps:
      - checkout
      - node/install0packages
      - run:
        name: 'seed database'
        command: npm run db:seed